import { Metadata } from "next";
import Link from "next/link";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms of Use | Bibliothèque",
  description: "Terms governing use of Bibliothèque.",
};

const serif = "'Georgia', serif";
const mono = "'Courier New', monospace";
const ink = "#1A1816";
const ink2 = "#6B6760";
const ink3 = "#9A9590";
const border_ = "#E5E1D8";
const blue = "#1D4ED8";
const cream = "#FAFAF7";

export default function TermsPage() {
  return (
    <div style={{ background: cream, color: ink, minHeight: "100vh", fontFamily: serif }}>
      <div style={{ borderBottom: `0.5px solid ${border_}`, background: cream }}>
        <div style={{ maxWidth: 680, margin: "0 auto", padding: "16px 24px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <Link href="/" style={{ textDecoration: "none" }}>
            <span style={{ fontSize: 20, fontStyle: "italic", fontWeight: 400, color: ink, letterSpacing: "-.025em" }}>
              Biblioth<span style={{ color: blue }}>è</span>que
            </span>
          </Link>
          <Link href="/" style={{ fontFamily: mono, fontSize: 11, color: ink3, textDecoration: "none" }}>Home</Link>
        </div>
      </div>

      <main style={{ maxWidth: 680, margin: "0 auto", padding: "48px 24px 60px" }}>
        <h1 style={{ fontSize: 36, fontWeight: 400, fontStyle: "italic", letterSpacing: "-.02em", marginBottom: 8 }}>Terms of Use</h1>
        <p style={{ fontFamily: mono, fontSize: 11, color: ink3, marginBottom: 32 }}>Effective: March 2026</p>

        {[
          { title: "The service", body: "Bibliothèque is a living library operated by TMOS13, LLC. Sessions are AI-powered conversations governed by protocol. Responses are generated, not authored by humans in real time. The texts in the library are sourced from the public domain or used under license." },
          { title: "Use", body: "You may use Bibliothèque for personal, educational, and research purposes. Anonymous visitors receive 5 turns per session. Registered users receive additional turns per their subscription tier. You may not use the service to generate content that violates applicable law." },
          { title: "AI-generated content", body: "Session responses are generated by AI (Claude, by Anthropic) operating under TMOS13 protocol governance. While sessions are grounded in source texts and governed by editorial protocols, AI-generated content may contain errors. Bibliothèque is not a substitute for professional advice in any domain." },
          { title: "Intellectual property", body: "Source texts in the library are in the public domain or used under license. Pack protocols and the TMOS13 engine are proprietary to TMOS13, LLC. Session transcripts belong to you. You may not reproduce, redistribute, or commercially exploit the platform, its protocols, or its engine." },
          { title: "Acceptable use", body: "Do not attempt to extract, reverse-engineer, or circumvent the protocol governance layer. Do not use sessions to generate harmful, illegal, or abusive content. Do not impersonate the platform or its sessions." },
          { title: "Limitation of liability", body: "Bibliothèque is provided as-is. TMOS13, LLC is not liable for decisions made based on AI-generated session content. Use your judgment." },
          { title: "Changes", body: "We may update these terms. Continued use constitutes acceptance. Material changes will be posted here." },
          { title: "Contact", body: "Questions about these terms: hello@tmos13.ai" },
        ].map(s => (
          <section key={s.title} style={{ marginBottom: 28 }}>
            <h2 style={{ fontSize: 18, fontWeight: 400, fontStyle: "italic", marginBottom: 8 }}>{s.title}</h2>
            <p style={{ fontSize: 15, lineHeight: 1.75, color: ink2 }}>{s.body}</p>
          </section>
        ))}

        <p style={{ fontFamily: mono, fontSize: 10, color: ink3, marginTop: 32 }}>TMOS13, LLC · Jersey City, NJ</p>
      </main>

      <SiteFooter />
    </div>
  );
}
